### PR TITLE
Add Ruby 2.5 to travis build matrix

### PR DESCRIPTION
**Pull request by devonestes**
Maybe it's time to drop support for those versions of Ruby that are no
longer being updated? 2.1 is currently end of life, and 2.2 is going to
be end of life'd at the end of March.

### CODE REVIEW

**Comment by miketheman** [comment]
See https://github.com/travis-ci/travis-ci/issues/8978 for current details on the Travis failure.

**Comment by devonestes** [comment]
That worked - thanks @miketheman!

**Comment by miketheman** [comment]
@devonestes Any news on merging?

**Comment by devonestes** [comment]
Nope! I’m not a maintainer, so it’s not up to me.

**Comment by miketheman** [comment]
Ah, so more like @calebthompson ?

**Comment by calebthompson** [comment]
@devonestes We typically follow the Ruby support schedule, so as we add 2.5.0, we'll drop 2.1. can you remove that from the matrix please? https://www.ruby-lang.org/en/downloads/branches/

**Comment by devonestes** [comment]
Cool, I dropped Ruby 2.1 and 2.2 as well, since that is end-of-life in 3 days. Also, I dropped Rails 4.0 and 4.1 since those are totally unsupported as well.

**Comment by calebthompson** [comment]
Thanks, @devonestes!

**Pull request merged**
