### PR TITLE
Update Travis Configuration

### PR DESCRIPTION
**Pull request by derekprior**
* Use the latest version of Ruby 2.1
* Add Ruby 2.2.0 to the testing matrix
* Enable the Travis container infrastructure (sudo: false)
* Disable bundler cache. We want Travis to resolve and install
 dependencies each time, as we want to know about issues that pop up
 with newer dependency versions.

### CODE REVIEW

**Comment by calebthompson** [comment]
Yup, but you've failures.

**Comment by derekprior** [comment]
Sure do. Not sure why. Going to try it without the container settings.

**Comment by derekprior** [comment]
... Interesting...

**Comment by calebthompson** [comment]
Yes it is. Our builds aren't super long though, so I'm happy to take what we can get here.

**Comment by derekprior** [comment]
Merging without the container infrastructure changes if this passes.

**Pull request merged**
